application: medmenrva
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/.*
  script: admin.APPLICATION
  login: admin

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest
